// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLN75HDy0ERI_NuKSnD-cNINFLZ-3t-qA',
    appId: '1:341801448801:web:08b3039a9b2b7c1b934120',
    messagingSenderId: '341801448801',
    projectId: 'jay-janki-electronics',
    authDomain: 'jay-janki-electronics.firebaseapp.com',
    storageBucket: 'jay-janki-electronics.firebasestorage.app',
    measurementId: 'G-E73Z9NJBNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHuZbkatN9V8lAI5iR6AO-gH6GsztbU7E',
    appId: '1:341801448801:android:3051453fc1a29968934120',
    messagingSenderId: '341801448801',
    projectId: 'jay-janki-electronics',
    storageBucket: 'jay-janki-electronics.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHuZbkatN9V8lAI5iR6AO-gH6GsztbU7E',
    appId: '1:341801448801:windows:873c513fc1a29968934120',
    messagingSenderId: '341801448801',
    projectId: 'jay-janki-electronics',
    authDomain: 'jay-janki-electronics.firebaseapp.com',
    storageBucket: 'jay-janki-electronics.firebasestorage.app',
    measurementId: 'G-E73Z9NJBNP',
  );
}
